[settings]
experimental=true

[tools]
#Development
starship="latest"
neovim="latest"
ripgrep="latest"
tmux="latest"
glow="latest"
fzf="latest"
bat="latest"
fd="latest"
yq="latest"

#Language
go="latest"
lua="latest"
rust="latest"
node="latest"
python="latest"
terraform="latest"

#Infrastructure
kubectl="latest"
argocd="latest"
awscli = "latest"
helm="latest"
k9s="latest"
gh="latest"
